In [1]:
#importing the libraries
import pandas as pd
import numpy as np
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [2]:
#reading the training txt file and naming the columns
train_df = pd.read_csv("train_data.txt",
                       engine="python",
                       sep=" ::: ",
                       names=["id", "movie", "genre", "Description"])
train_df

id                                       movie        genre  \
0          1                Oscar et la dame rose (2009)        drama   
1          2                                Cupid (1997)     thriller   
2          3            Young, Wild and Wonderful (1980)        adult   
3          4                       The Secret Sin (1915)        drama   
4          5                      The Unrecovered (2007)        drama   
...      ...                                         ...          ...   
54209  54210                             "Bonino" (1953)       comedy   
54210  54211                 Dead Girls Don't Cry (????)       horror   
54211  54212   Ronald Goedemondt: Ze bestaan echt (2008)  documentary   
54212  54213                    Make Your Own Bed (1944)       comedy   
54213  54214  Nature's Fury: Storm of the Century (2006)      history   

                                             Description  
0      Listening in to a conversation between his doc...  
1      A brother and sister with a past incestuous re...  
2      As the bus empties the students for their fiel...  
3      To help their unemployed father make ends meet...  
4      The film's title refers not only to the un-rec...  
...                                                  ...  
54209  This short-lived NBC live sitcom centered on B...  
54210  The NEXT Generation of EXPLOITATION. The siste...  
54211  Ze bestaan echt, is a stand-up comedy about gr...  
54212  Walter and Vivian live in the country and have...  
54213  On Labor Day Weekend, 1935, the most intense h...  

[54214 rows x 4 columns]

In [3]:
#reading the sample test txt file and naming the columns

new_test_df = pd.read_csv("test_data.txt",
                       engine="python",
                       sep=" ::: ",
                       names=["id", "movie","Description"])
new_test_df

id                           movie  \
0          1            Edgar's Lunch (1998)   
1          2        La guerra de papá (1977)   
2          3     Off the Beaten Track (2010)   
3          4          Meu Amigo Hindu (2015)   
4          5               Er nu zhai (1955)   
...      ...                             ...   
54195  54196  "Tales of Light & Dark" (2013)   
54196  54197     Der letzte Mohikaner (1965)   
54197  54198             Oliver Twink (2007)   
54198  54199               Slipstream (1973)   
54199  54200       Curitiba Zero Grau (2010)   

                                             Description  
0      L.R. Brane loves his life - his car, his apart...  
1      Spain, March 1964: Quico is a very naughty chi...  
2      One year in the life of Albin and his family o...  
3      His father has died, he hasn't spoken with his...  
4      Before he was known internationally as a marti...  
...                                                  ...  
54195  Covering multiple genres, Tales of Light & Dar...  
54196  As Alice and Cora Munro attempt to find their ...  
54197  A movie 169 years in the making. Oliver Twist,...  
54198  Popular, but mysterious rock D.J Mike Mallard ...  
54199  Curitiba is a city in movement, with rhythms a...  

[54200 rows x 3 columns]

In [4]:
#seperating the dependent variable from the dataset
y_train = train_df.genre
print(y_train)



0              drama
1           thriller
2              adult
3              drama
4              drama
            ...     
54209         comedy
54210         horror
54211    documentary
54212         comedy
54213        history
Name: genre, Length: 54214, dtype: object


In [5]:
#convering the dependent feature from categorical variable into numerical variable
le = LabelEncoder()
le.fit(y_train)
le.classes_
y_train = le.transform(y_train)
y_train

array([ 8, 24,  1, ...,  7,  5, 12])

In [6]:
# converting the description column  from Series type to numpy array
desc = train_df['Description']
for _ in range(2):
    print(desc[_])
    print("\n")
desc_arr = np.array(desc.tolist())
print(type(desc_arr))

Listening in to a conversation between his doctor and parents, 10-year-old Oscar learns what nobody has the courage to tell him. He only has a few weeks to live. Furious, he refuses to speak to anyone except straight-talking Rose, the lady in pink he meets on the hospital stairs. As Christmas approaches, Rose uses her fantastical experiences as a professional wrestler, her imagination, wit and charm to allow Oscar to live life and love to the full, in the company of his friends Pop Corn, Einstein, Bacon and childhood sweetheart Peggy Blue.


A brother and sister with a past incestuous relationship have a current murderous relationship. He murders the women who reject him and she murders the women who get too close to him.


<class 'numpy.ndarray'>


In [7]:
#making a function that converts the input dataset into xtrain and features
def extract_features(description_array):
    wordnet = WordNetLemmatizer()
    tfidf = TfidfVectorizer(max_features=7000)

    corpus =[]

    for i,des in enumerate(description_array):
        if (i%1000==0):
            print(">>> Iteration # ",i)
        var = re.sub("[^a-zA-Z]", " ", des) # just keeping the alphabets and removing special characters and numbers
        var = var.lower() # lowercasing all
        var = var.split() # splits on space to get a list of words
        var = [wordnet.lemmatize(word) for word in var if not word in set(stopwords.words('english'))] # Lemmatizing all the words
        var = ' '.join(var)
        corpus.append(var)
    X_train = tfidf.fit_transform(corpus).toarray()
    features = tfidf.get_feature_names_out()
    return X_train,features



In [8]:
X_train, features = extract_features(desc_arr)


>>> Iteration #  0
>>> Iteration #  1000
>>> Iteration #  2000
>>> Iteration #  3000
>>> Iteration #  4000
>>> Iteration #  5000
>>> Iteration #  6000
>>> Iteration #  7000
>>> Iteration #  8000
>>> Iteration #  9000
>>> Iteration #  10000
>>> Iteration #  11000
>>> Iteration #  12000
>>> Iteration #  13000
>>> Iteration #  14000
>>> Iteration #  15000
>>> Iteration #  16000
>>> Iteration #  17000
>>> Iteration #  18000
>>> Iteration #  19000
>>> Iteration #  20000
>>> Iteration #  21000
>>> Iteration #  22000
>>> Iteration #  23000
>>> Iteration #  24000
>>> Iteration #  25000
>>> Iteration #  26000
>>> Iteration #  27000
>>> Iteration #  28000
>>> Iteration #  29000
>>> Iteration #  30000
>>> Iteration #  31000
>>> Iteration #  32000
>>> Iteration #  33000
>>> Iteration #  34000
>>> Iteration #  35000
>>> Iteration #  36000
>>> Iteration #  37000
>>> Iteration #  38000
>>> Iteration #  39000
>>> Iteration #  40000
>>> Iteration #  41000
>>> Iteration #  42000
>>> Iteration #  43000
>

In [9]:
#printing the xtrain and extracted features
print(X_train.shape)
print(X_train)
print(features)
print(features.shape)


(54214, 7000)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['aaron' 'abandon' 'abandoned' ... 'zombie' 'zone' 'zoo']
(7000,)


In [10]:
#seperating the dataset into training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train,y_train,test_size=0.20,random_state=0)

In [11]:
print(X_train.shape)
print(X_test.shape)

(43371, 7000)
(10843, 7000)


In [12]:
#building a Navie Bayers model and training it using training variables
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [13]:
print(len(y_train))

43371


In [14]:
#predicting the test data
y_pred = model.predict(X_test)
y_pred

array([ 7,  8,  7, ..., 21,  7,  7])

In [15]:
np.printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


[[ 7  7]
 [ 8  8]
 [ 7  7]
 ...
 [21 21]
 [ 7 12]
 [ 7  7]]


In [16]:
#printing the confusion matrix
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test,y_pred)
conf_mat

array([[  20,    0,    0,    0,    0,   22,    0,   47,  154,    0,    0,
           0,    0,    2,    0,    0,    0,    0,    0,    0,    0,    3,
           0,    0,    0,    0,    0],
       [   0,    3,    4,    0,    0,   42,    0,    8,   45,    0,    0,
           0,    0,    1,    0,    0,    0,    0,    0,    0,    0,    7,
           0,    0,    0,    0,    0],
       [   1,    3,   14,    0,    0,   21,    0,   41,   68,    0,    0,
           0,    0,    2,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   1,    0,    0,    0,    0,   33,    0,   32,   34,    0,    0,
           0,    0,    2,    0,    0,    0,    0,    0,    0,    0,    5,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,   41,   11,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   2,    0,    0,    0,    0,  697,    0,  154,  633,    

In [17]:
#predicting the accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

0.5246702941990224


In [18]:
#taking a sample of new test data
new_test_df = new_test_df.sample(frac=0.05)


In [19]:
# converting the description column  from Series type to numpy array
desc = new_test_df['Description']
print(desc)
desc_arr = np.array(desc.tolist())
print(type(desc_arr))


11723    Matt, a home arcade games programmer runs into...
24212    The documentary film "Janus' Legacy: Refugee P...
16939    An old lady and her dog are fed up of crime an...
399      Kuhu, a 9 year old girl, drowns in a lake in N...
17880    Jennifer, a young, ambitious executive running...
                               ...                        
32337    Hans Schabe, whose last name means cockroach i...
12288    For nearly two centuries, generations of knigh...
44480    Have you ever been in love with anyone? Better...
19806    Liguo is an aspiring cartoonist, forced by rea...
32620    This documentary reveals the important role of...
Name: Description, Length: 2710, dtype: object
<class 'numpy.ndarray'>


In [20]:
#making a function that converts the input dataset into xtrain and features
def extract_features(description_array):
    wordnet = WordNetLemmatizer()
    tfidf = TfidfVectorizer(max_features=7000)

    corpus =[]

    for i,des in enumerate(description_array):
        if (i%1000==0):
            print(">>> Iteration # ",i)
        var = re.sub("[^a-zA-Z]", " ", des) # just keeping the alphabets and removing special characters and numbers
        var = var.lower() # lowercasing all
        var = var.split() # splits on space to get a list of words
        var = [wordnet.lemmatize(word) for word in var if not word in set(stopwords.words('english'))] # Lemmatizing all the words
        var = ' '.join(var)
        corpus.append(var)
    new_X_test = tfidf.fit_transform(corpus).toarray()
    features1 = tfidf.get_feature_names_out()
    return new_X_test,features1


>>> Iteration #  0
>>> Iteration #  1000
>>> Iteration #  2000
(2710, 7000)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(7000,)


In [24]:
#printing the xtest and extracted features
print(new_X_test.shape)
print(type(new_X_test))
print(type(features1))
print(features1.shape)


(2710, 7000)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(7000,)


In [26]:
#predicting a new_genre
new_genre_pred = model.predict(new_X_test)

In [27]:
#printing the new genre
print(new_genre_pred)

[7 8 7 ... 9 7 7]
